[package]
name = "rustengan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
serde = { version = "1.0.160", features = ["derive", "std"] }
serde_json = "1.0.96"
rand = "0.8.5"